title: "Brett MICHEL"
description: "Portfolio ESIEE-IMAC"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr

<object data="Portfolio_Brett_MICHEL_2026.pdf" width="1000" height="1000" type='application/pdf'/>
